//go:build !ignore_autogenerated

/*
Copyright 2023 The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kubevela/workflow/api/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlane) DeepCopyInto(out *ClusterPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlane.
func (in *ClusterPlane) DeepCopy() *ClusterPlane {
	if in == nil {
		return nil
	}
	out := new(ClusterPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlaneList) DeepCopyInto(out *ClusterPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlaneList.
func (in *ClusterPlaneList) DeepCopy() *ClusterPlaneList {
	if in == nil {
		return nil
	}
	out := new(ClusterPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlaneRevision) DeepCopyInto(out *ClusterPlaneRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlaneRevision.
func (in *ClusterPlaneRevision) DeepCopy() *ClusterPlaneRevision {
	if in == nil {
		return nil
	}
	out := new(ClusterPlaneRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlaneRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlaneRevisionList) DeepCopyInto(out *ClusterPlaneRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPlaneRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlaneRevisionList.
func (in *ClusterPlaneRevisionList) DeepCopy() *ClusterPlaneRevisionList {
	if in == nil {
		return nil
	}
	out := new(ClusterPlaneRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPlaneRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlaneRevisionSpec) DeepCopyInto(out *ClusterPlaneRevisionSpec) {
	*out = *in
	in.PlaneSnapshot.DeepCopyInto(&out.PlaneSnapshot)
	in.RevisionMeta.DeepCopyInto(&out.RevisionMeta)
	if in.Compression != nil {
		in, out := &in.Compression, &out.Compression
		*out = new(CompressionSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlaneRevisionSpec.
func (in *ClusterPlaneRevisionSpec) DeepCopy() *ClusterPlaneRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPlaneRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlaneRevisionStatus) DeepCopyInto(out *ClusterPlaneRevisionStatus) {
	*out = *in
	if in.ActiveInClusters != nil {
		in, out := &in.ActiveInClusters, &out.ActiveInClusters
		*out = make([]ClusterReference, len(*in))
		copy(*out, *in)
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceTrackerRef != nil {
		in, out := &in.ResourceTrackerRef, &out.ResourceTrackerRef
		*out = new(ResourceTrackerReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlaneRevisionStatus.
func (in *ClusterPlaneRevisionStatus) DeepCopy() *ClusterPlaneRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPlaneRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlaneSpec) DeepCopyInto(out *ClusterPlaneSpec) {
	*out = *in
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(OwnerInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]PlaneComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Traits != nil {
		in, out := &in.Traits, &out.Traits
		*out = make([]PlaneTrait, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]PlanePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]PlaneOutput, len(*in))
		copy(*out, *in)
	}
	if in.CrossClusterInputs != nil {
		in, out := &in.CrossClusterInputs, &out.CrossClusterInputs
		*out = make([]CrossClusterInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlaneSpec.
func (in *ClusterPlaneSpec) DeepCopy() *ClusterPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlaneStatus) DeepCopyInto(out *ClusterPlaneStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.CurrentRevision != nil {
		in, out := &in.CurrentRevision, &out.CurrentRevision
		*out = new(RevisionReference)
		**out = **in
	}
	if in.ComponentHealth != nil {
		in, out := &in.ComponentHealth, &out.ComponentHealth
		*out = make([]ComponentHealthStatus, len(*in))
		copy(*out, *in)
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceTrackerRef != nil {
		in, out := &in.ResourceTrackerRef, &out.ResourceTrackerRef
		*out = new(ResourceTrackerReference)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlaneStatus.
func (in *ClusterPlaneStatus) DeepCopy() *ClusterPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReference.
func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentHealthStatus) DeepCopyInto(out *ComponentHealthStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentHealthStatus.
func (in *ComponentHealthStatus) DeepCopy() *ComponentHealthStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompressionSpec) DeepCopyInto(out *CompressionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompressionSpec.
func (in *CompressionSpec) DeepCopy() *CompressionSpec {
	if in == nil {
		return nil
	}
	out := new(CompressionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossClusterInput) DeepCopyInto(out *CrossClusterInput) {
	*out = *in
	if in.FallbackValue != nil {
		in, out := &in.FallbackValue, &out.FallbackValue
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossClusterInput.
func (in *CrossClusterInput) DeepCopy() *CrossClusterInput {
	if in == nil {
		return nil
	}
	out := new(CrossClusterInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnerInfo) DeepCopyInto(out *OwnerInfo) {
	*out = *in
	if in.Contacts != nil {
		in, out := &in.Contacts, &out.Contacts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnerInfo.
func (in *OwnerInfo) DeepCopy() *OwnerInfo {
	if in == nil {
		return nil
	}
	out := new(OwnerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaneComponent) DeepCopyInto(out *PlaneComponent) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make(apiv1alpha1.StepInputs, len(*in))
		copy(*out, *in)
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make(apiv1alpha1.StepOutputs, len(*in))
		copy(*out, *in)
	}
	if in.Traits != nil {
		in, out := &in.Traits, &out.Traits
		*out = make([]PlaneTrait, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaneComponent.
func (in *PlaneComponent) DeepCopy() *PlaneComponent {
	if in == nil {
		return nil
	}
	out := new(PlaneComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaneOutput) DeepCopyInto(out *PlaneOutput) {
	*out = *in
	out.ValueFrom = in.ValueFrom
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaneOutput.
func (in *PlaneOutput) DeepCopy() *PlaneOutput {
	if in == nil {
		return nil
	}
	out := new(PlaneOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaneOutputValueFrom) DeepCopyInto(out *PlaneOutputValueFrom) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaneOutputValueFrom.
func (in *PlaneOutputValueFrom) DeepCopy() *PlaneOutputValueFrom {
	if in == nil {
		return nil
	}
	out := new(PlaneOutputValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanePolicy) DeepCopyInto(out *PlanePolicy) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanePolicy.
func (in *PlanePolicy) DeepCopy() *PlanePolicy {
	if in == nil {
		return nil
	}
	out := new(PlanePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaneSnapshot) DeepCopyInto(out *PlaneSnapshot) {
	*out = *in
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(OwnerInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]PlaneComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Traits != nil {
		in, out := &in.Traits, &out.Traits
		*out = make([]PlaneTrait, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]PlanePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]PlaneOutput, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaneSnapshot.
func (in *PlaneSnapshot) DeepCopy() *PlaneSnapshot {
	if in == nil {
		return nil
	}
	out := new(PlaneSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaneTrait) DeepCopyInto(out *PlaneTrait) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaneTrait.
func (in *PlaneTrait) DeepCopy() *PlaneTrait {
	if in == nil {
		return nil
	}
	out := new(PlaneTrait)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceTrackerReference) DeepCopyInto(out *ResourceTrackerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceTrackerReference.
func (in *ResourceTrackerReference) DeepCopy() *ResourceTrackerReference {
	if in == nil {
		return nil
	}
	out := new(ResourceTrackerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionMeta) DeepCopyInto(out *RevisionMeta) {
	*out = *in
	in.Created.DeepCopyInto(&out.Created)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionMeta.
func (in *RevisionMeta) DeepCopy() *RevisionMeta {
	if in == nil {
		return nil
	}
	out := new(RevisionMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionReference) DeepCopyInto(out *RevisionReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionReference.
func (in *RevisionReference) DeepCopy() *RevisionReference {
	if in == nil {
		return nil
	}
	out := new(RevisionReference)
	in.DeepCopyInto(out)
	return out
}
